Add response_format support for openai and a way to set the functions
henomis/lingoose pull request #170
Opened 2024-02-23 16:07 UTC by Arttii

## Description

I needed support for the JSON output that OpenAI supports by setting the type. This is already supported by the underlying client.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] No tests

## Checklist:

- [X] I have read the [Contributing documentation](https://github.com/henomis/lingoose/blob/main/CONTRIBUTING.md).
- [ X] I have read the [Code of conduct documentation](https://github.com/henomis/lingoose/blob/main/CODE_OF_CONDUCT.md).
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [X] I have checked my code and corrected any misspellings

2024-04-10 08:00 UTC, BabySid commented
hi, I do need this feature too. Is there a plan to merge this PR? thanks @henomis

2024-04-10 08:15 UTC, henomis commented
> hi, I do need this feature too. Is there a plan to merge this PR? thanks @henomis

@BabySid this PR needs some refactor.

2024-04-11 02:15 UTC, BabySid commented
> > hi, I do need this feature too. Is there a plan to merge this PR? thanks @henomis
> 
> @BabySid this PR needs some refactor.

got. Thanks for the reply

2024-04-14 10:07 UTC, Arttii commented
@henomis please let me know, what you think should be changed. Would be happy to incorporate it.

2024-04-14 10:13 UTC, henomis commented
> @henomis please let me know, what you think should be changed. Would be happy to incorporate it.

@Arttii just follow the review comments.

2024-04-14 10:15 UTC, henomis requested changes

2024-04-14 10:15 UTC, henomis commented on go.sum
> +github.com/sashabaranov/go-openai v1.21.0/go.mod h1:lj5b/K+zjTSFxVLijLSTDZuP7adOgerWeFyZLUhAKRg=
This is out of scope of this PR.

2024-04-14 10:15 UTC, henomis commented on llm/openai/common.go
> +	GPT4Turbo20240409     Model = openai.GPT4Turbo20240409
Out of Scope

2024-04-14 10:15 UTC, henomis commented on llm/openai/openai.go
> +			Function: &openai.FunctionDefinition{
Out of scope

2024-04-14 10:28 UTC, Arttii commented on llm/openai/openai.go
> +	responseFormat   openai.ChatCompletionResponseFormatType
Should we use a local alias for this or what is your preference?

2024-04-14 10:30 UTC, Arttii commented on thread/thread.go
> +		panic(c)
This is  an interesting question as we should at least surface the error. This tripped me up a few times as the llm was just being prompted with an empty prompt essentially. Should we log or what is your preference?

2024-04-14 10:31 UTC, Arttii commented on go.sum
> +github.com/sashabaranov/go-openai v1.21.0/go.mod h1:lj5b/K+zjTSFxVLijLSTDZuP7adOgerWeFyZLUhAKRg=
Fair enough, I will remove this.

2024-04-14 10:31 UTC, Arttii commented on llm/openai/openai.go
> +
Why is this out of scope?

2024-04-15 07:11 UTC, henomis requested changes

2024-04-15 07:11 UTC, henomis commented on llm/openai/openai.go
> +	responseFormat   openai.ChatCompletionResponseFormatType
Yes use an alias, see the comment below.

2024-04-15 07:11 UTC, henomis commented on llm/openai/openai.go
> +func (o *OpenAI) WithResponseFormat(format openai.ChatCompletionResponseFormatType) *OpenAI {
Lingoose's users must deal with lingoose types.

2024-04-15 07:11 UTC, henomis commented on llm/openai/openai.go
> +
I'm not 100% sure of this method and this change must be discussed.

2024-05-20 03:21 UTC, BabySid commented
Hi, @henomis  It seems that this PR has been on hold for a long time. Does the lingoose project have any plans to develop this feature? To be honest, this feature is still very important for openai.  I also know that this PR is currently in a very awkward situation, and the author may not be able to continue development due to some unknown reasons. It would be a very commendable thing if the project can integrate this feature.

2024-05-20 06:14 UTC, henomis commented
@BabySid 
I'll open a new PR for this feature.

2024-05-20 06:31 UTC, henomis commented
Implemented here: https://github.com/henomis/lingoose/pull/199

2024-05-20 06:31 UTC, closed without merging